### ISSUE TITLE
Can not install the software using pip

### ISSUE THREAD

**Issue by jtklein** [dongzhang0725/PhyloSuite#19]
On MacOS Catalina, installing the software via 'pip3 install PhyloSuite' gives the following error:

ERROR: Could not find a version that satisfies the requirement sip<4.20,>=4.19.4 (from PyQt5==5.10.1->PhyloSuite) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0)
ERROR: No matching distribution found for sip<4.20,>=4.19.4 (from PyQt5==5.10.1->PhyloSuite)

**Comment by dongzhang0725** [comment]
Hi Johannes,
My guess is that you used a new version of Python (like Python 3.8). As PhyloSuite was developed on the Python 3.6.7 platform, it may not work with the newer versions (I encounter similar problem in Python 3.8). I suggest that you try to use python 3.6 to install PhyloSuite. If you encounter another problem, please do not hesitate to contact me.

**Comment by jtklein** [comment]
My python --version was 3.7.7
Maybe you should update the documentation accordingly: "First, Python (version _higher than 3.6_) should be installed and added to the environment variable in your computer."

**Comment by dongzhang0725** [comment]
Thank you for your suggestion, when I wrote the document, the newest Python version was 3.7.1, and I tested all Python versions higher than 3.6 on PhyloSuite successfully. I am sorry for the misleading message, I will try to figure out why the new Python version failed to run PhyloSuite and update the document accordingly in the next update. 
By the way, you can easily simultaneously run multiple Python versions on a single computer. You may try to install Python 3.6.7 without uninstalling 3.7.7.
