### ISSUE TITLE
IQ tree

### ISSUE THREAD

**Issue by quillby** [dongzhang0725/PhyloSuite#2]
When using ModelFinder or PartitionFinder the aligned file is not found and program is terminating.
IQ-tree: using menu 'Phylogeny' and IQ-tree with an already aligned file creates an error:
Traceback (most recent call last):
  File "codes\Lg_IQTREE.py", line 187, in on_pushButton_clicked
TypeError: not all arguments converted during string formatting

**Comment by dongzhang0725** [comment]
Thank you for reporting this bug, I have fixed it, please update the software through `Settings-->Check for Updates` and try again.
