### ISSUE TITLE
外群能否直接和内群放在一起比对，串联？

### ISSUE THREAD

**Issue by zhangmin20201021** [dongzhang0725/PhyloSuite#20]
自己实验得到的各基因序列，没有用Phylosuite提取基因，能否把外群和内群放在一起进行比对，然后串联？这样在Phylosuite的建树步骤里就不用选择Outgroup可以吗？

**Comment by dongzhang0725** [comment]
外群和内群肯定是要放在一起去比对、串联的

**Comment by zhangmin20201021** [comment]
我看您的视频讲解里是建树时勾选的外群，前面比对和串联时没有用外群吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 晚上7:15
收件人:&nbsp;"dongzhang0725/PhyloSuite"<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;"张敏"<1961187746@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 外群能否直接和内群放在一起比对，串联？ (#20)





 
外群和内群肯定是要放在一起去比对、串联的

**Comment by dongzhang0725** [comment]
视频里面没有讲加外群的事情，但是自己建树的时候最好加进去。

**Comment by zhangmin20201021** [comment]
张老师我是这么理解的，前面比对，串联时加了外群，后面建树时“Outgroup”那里就不用勾选外群序列了对吗？
另外，您视频里建树时勾选的那些外群序列是从NCBI直接下载来用的呢还是经过处理的呀？
问题比较奇怪，麻烦张老师了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 晚上7:33
收件人:&nbsp;"dongzhang0725/PhyloSuite"<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;"张敏"<1961187746@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 外群能否直接和内群放在一起比对，串联？ (#20)





 
视频里面没有讲加外群的事情，但是自己建树的时候最好加进去。

**Comment by dongzhang0725** [comment]
比对、串联加外群和后面建树勾选外群不是相互冲突的步骤，而是并存的。建议多补充一些系统发育树构建的基础知识。NCBI的序列直接下载就能用了。

**Comment by zhangmin20201021** [comment]
张老师，这是MACSE报错的提示，主要是什么原因呢？需要怎么解决？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 晚上9:35
收件人:&nbsp;"dongzhang0725/PhyloSuite"<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;"张敏"<1961187746@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 外群能否直接和内群放在一起比对，串联？ (#20)





 
比对、串联加外群和后面建树勾选外群不是相互冲突的步骤，而是并存的。建议多补充一些系统发育树构建的基础知识。NCBI的序列直接下载就能用了。
