### ISSUE TITLE
关于MACSE出错的问题

### ISSUE THREAD

**Issue by zhangmin20201021** [dongzhang0725/PhyloSuite#21]
![4 3T`YQG8K51P`GDZG{33R6](https://user-images.githubusercontent.com/73221259/97132652-994bc880-1782-11eb-862f-38c0cc298bb5.png)
![CW2XD86W(85XSIBVMM54MPC](https://user-images.githubusercontent.com/73221259/97132658-9b158c00-1782-11eb-8107-2a891e1d1e60.png)

**Comment by dongzhang0725** [comment]
PhyloSuite是安装到C盘的吗？

**Comment by zhangmin20201021** [comment]
不是的，安装到E盘的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zhang&amp;nbsp;dong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月30日(星期五) 中午11:41
收件人:&nbsp;&quot;dongzhang0725/PhyloSuite&quot;<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;&quot;zhangmin20201021&quot;<1961187746@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 关于MACSE出错的问题 (#21)

**Comment by dongzhang0725** [comment]
试试以管理员身份运行phylosuite

**Comment by zhangmin20201021** [comment]
张老师，我重新安装了JavaSetup8u271,然后按照您的指导以管理员身份运行了，还是出现这样的报错。主要是什么原因呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 中午1:03
收件人:&nbsp;"dongzhang0725/PhyloSuite"<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;"张敏"<1961187746@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 关于MACSE出错的问题 (#21)





 
试试以管理员身份运行phylosuite

**Comment by dongzhang0725** [comment]
试试在phylosuite安装目录的plugins文件夹里面找到MACSE.jar这个文件，然后设置始终以管理员身份运行

**Comment by zhangmin20201021** [comment]
以管理员身份运行了MACSE.jar，还是同样的报错提示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 晚上9:06
收件人:&nbsp;"dongzhang0725/PhyloSuite"<PhyloSuite@noreply.github.com&gt;;
抄送:&nbsp;"张敏"<1961187746@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] 关于MACSE出错的问题 (#21)





 
试试在phylosuite安装目录的plugins文件夹里面找到MACSE.jar这个文件，然后设置始终以管理员身份运行

**Comment by dongzhang0725** [comment]
那不确定是哪里的原因，一般这种情况用管理员身份运行就行了。或许也可以试试只用1个核运行看看。
