### ISSUE TITLE
打开PhyloSuite弹出报错界面

### ISSUE THREAD

**Issue by zhangmin20201021** [dongzhang0725/PhyloSuite#22]
![PhyloSuite打开报错](https://user-images.githubusercontent.com/73221259/105795450-d2851600-5fc7-11eb-98ab-76726f9bf2e1.png)

打开PhyloSuite弹出这个报错提醒是什么意思？忽略后也不影响PhyloSuite运行

**Comment by dongzhang0725** [comment]
不影响运行。在设置里面把自动检查更新关掉即可[image: image.png]

zhangmin20201021 <notifications@github.com> 于2021年1月26日周二 上午11:22写道：
