### ISSUE TITLE
PartitionFinder2结果直接载入Mrbayes时报错，报错窗口点击OK或者show details后软件直接闪退

### ISSUE THREAD

**Issue by Xiongxuemei** [dongzhang0725/PhyloSuite#23]
PartitionFinder2结果直接载入Mrbayes时报错，报错窗口点击OK或者show details后软件直接闪退
![image](https://user-images.githubusercontent.com/79627816/109119214-59700e80-777f-11eb-8788-6766230395a1.png)

**Comment by dongzhang0725** [comment]
可能是这个phylip文件造成的，将其转为标准的phy格式再试试看
![image](https://user-images.githubusercontent.com/15956921/109121921-d650b780-7782-11eb-94d3-2ac35c8e2595.png)

**Comment by Xiongxuemei** [comment]
嗯嗯，我用其他软件试试，在PhyloSuite的Convert Sequence Format转换格式时，也报错
![image](https://user-images.githubusercontent.com/79627816/109147654-36098b80-77a0-11eb-8c9d-d833b0d8c5eb.png)  
![image](https://user-images.githubusercontent.com/79627816/109147724-4f123c80-77a0-11eb-9618-6d8d6c9371a2.png)

**Comment by dongzhang0725** [comment]
用其它软件转格式试试，mrbayes之所以报错就是因为转格式时报错了
