### ISSUE TITLE
A discussion of the principle of renewal（更新原理）

### ISSUE THREAD

**Issue by sasa146** [dongzhang0725/PhyloSuite#25]
I'm also working on a bioinformatics software. Now it's the closing stage. What we need to do now is to update my software online. My solution is to call the upgrade program and close the main program. All the upgrade tasks are performed by the upgrade program. But I found that your software has no similar upgrade program. How can I do that? What we can think of is to separate UI code from non UI code, and then update non UI code without closing the main window. However, we have no experimental verification. What's the real situation? Is it easy to implement? We are still novices, and we hope that the boss will not hesitate to give us advice.
我也在做一个生物信息学软件，现在到了收尾阶段，我们现在要做的是在线更新我的软件，我采用的方案是，调用升级程序，主程序关闭，所有的升级任务都由升级程序来执行，但是我发现您的软件，并没有类似的升级程序，请问是怎么做到的？我们能想到的是，将UI代码与非UI代码分离，然后在不关闭主窗口的情况下，去更新非UI代码，但是我们没有实验验证，请问真实情况是怎样的，容易实现吗？我们还是新手，还希望大佬不吝赐教。

**Comment by dongzhang0725** [comment]
Appologize, I am too busy these days. First dowload all the files from the new version, then rename the old files with the same name, finally
