### ISSUE TITLE
Bacterial outgroups

### ISSUE THREAD

**Issue by MitosChondros** [dongzhang0725/PhyloSuite#26]
Hi,

I'm really liking your software so far, but I was thinking that it would be great to have a curated set of alphaproteobacterial Genbank files come prepackaged with PhyloSuite so that trees can be anchored with an outgroup (really, only genes with homologs in mtDNA would need to be carefully curated). I am currently doing this myself for a few species by playing around with the Genbank file extract settings, but the nomenclature in bacterial files is far from standardized, and there are e.g., multiple different oxidases, so it's taking a while.

**Comment by dongzhang0725** [comment]
Hi,

I am sorry for the late reply, I am not quite sure what you mean by your question. Can you send your dataset for me to test?

Sincerely,
Dong
