### ISSUE TITLE
跑mrbayes的时候报的错，请问老师需要怎么解决？

### ISSUE THREAD

**Issue by wuhong46** [dongzhang0725/PhyloSuite#28]
Traceback (most recent call last):
  File "codes\src\factory.py", line 2824, in handleResponse
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 124: invalid continuation byte

**Comment by dongzhang0725** [comment]
Please provide the following information:
1. the version of PhyloSuite.
2. the command of mrbayes, this can be found on the top of the "show log" window

By the way, this seems not to be the error for mrbayes, it's the error of update function, so try to ignore it and run mrbayes directly.
