### ISSUE TITLE
提取序列时提示“...with no features...”

### ISSUE THREAD

**Issue by zhangmin20201021** [dongzhang0725/PhyloSuite#29]
利用phylosuite的“search in NCBI”功能提取线粒体基因，但某些基因组在提取多基因时会提示“...with no features...”，且结果文件为空，请问是什么原因？怎么解决？

**Comment by dongzhang0725** [comment]
应该是这个ID没有注释信息，你可以用对应的ID号搜索看看，并且show detail里面也会有显示这个序列的具体信息。

zhangmin20201021 ***@***.***> 于2021年7月7日周三 下午9:25写道：
