### ISSUE TITLE
ModelFinder

### ISSUE THREAD

**Issue by quillby** [dongzhang0725/PhyloSuite#3]
ModelFinder can't find aligned file in 'Workplace'. Clicking inside the Alignment File textbox will show no filename.
![afbeelding](https://user-images.githubusercontent.com/8212578/49703364-61761f00-fc04-11e8-9231-34f65c116c15.png)

**Comment by dongzhang0725** [comment]
We are not sure what happened here, please inspect carefully the concatenated file and check the log of the ModelFinder. You may drop both files here if you can't find what went wrong.
![t70gd4bosppb3 25ixfa](https://user-images.githubusercontent.com/15956921/49719896-6afd9680-fc99-11e8-9473-75c2e40d6b0a.png)
