### ISSUE TITLE
IQtree建树问题

### ISSUE THREAD

**Issue by awae876** [dongzhang0725/PhyloSuite#41]
老师您好，我在用IQtree时遇到了以下报错，请问是什么原因呢？
ERROR: phylokernelnew.h:3273: double PhyloTree::computeLikelihoodFromBufferGenericSIMD() [with VectorClass = Vec4d; bool FMA = true; bool SITE_MODEL = false]: Assertion `std::isfinite(tree_lh) && "Numerical underflow for lh-from-buffer"' failed.

**Comment by awae876** [comment]
> 老师您好，我在用IQtree时遇到了以下报错，请问是什么原因呢？ ERROR: phylokernelnew.h:3273: double PhyloTree::computeLikelihoodFromBufferGenericSIMD() [with VectorClass = Vec4d; bool FMA = true; bool SITE_MODEL = false]: Assertion `std::isfinite(tree_lh) && "Numerical underflow for lh-from-buffer"' failed.

尝试过在命令后加-safe 也不行

**Comment by dongzhang0725** [comment]
你设外群了吗，或许可以试试不设外群

**Comment by awae876** [comment]
> 你设外群了吗，或许可以试试不设外群

设不设外群都尝试过，有时候报错有时候不报错

**Comment by dongzhang0725** [comment]
可以发个邮件问下IQ-TREE的作者，或者在他们的google group提问，这个是IQ-TREE的内部报错。

**Comment by awae876** [comment]
> 可以发个邮件问下IQ-TREE的作者，或者在他们的google group提问，这个是IQ-TREE的内部报错。

好的，谢谢老师
