### ISSUE TITLE
A translation suggestion of self-translated_AA

### ISSUE THREAD

**Issue by Gjocund** [dongzhang0725/PhyloSuite#43]
Hello Doctor:
I hope that when extracting gene sequences, the result in self-translated_AA can be changed to a direct translation of the CDS_NUC sequences, i.e. with stop codons, for example,
TCCTAGAAT will be translated to:
S*N
but now the stop codon was neglected by the software ...
Thanks~

**Comment by dongzhang0725** [comment]
Hi there, 

Good suggestions, I will modify it as you suggested in the next version.

Sincerely, 
Dong
