### ISSUE TITLE
遇到的错误 Error encountered (7/02/2022)

### ISSUE THREAD

**Issue by Felipe3105** [dongzhang0725/PhyloSuite#46]
Traceback (most recent call last):
  File "codes\src\factory.py", line 2089, in slot
AttributeError: 'NoneType' object has no attribute 'group'

![Screenshot 2022-02-07 163601](https://user-images.githubusercontent.com/41596918/152859199-d66b2760-161a-4231-80da-6aca1bfefa6a.png)

**Comment by dongzhang0725** [comment]
see #38

**Comment by Felipe3105** [comment]
Thank you!
