### ISSUE TITLE
Check for updates报错

### ISSUE THREAD

**Issue by Haodegeiqian19** [dongzhang0725/PhyloSuite#51]
老师您好，Check for updates时报错，请问是什么问题呢？谢谢

Traceback (most recent call last):
  File "codes/src/factory.py", line 2089, in slot
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dongzhang0725** [comment]
由于网络原因，目前检查更新功能没法用。可以去官网下载最新版手动更新，B站视频有讲手动更新的方法。如果你是用的1.22版，那么就是最新版了，不用更新。新版本还在开发中。

**Comment by Haodegeiqian19** [comment]
好的，谢谢老师。
