### ISSUE TITLE
Can you introduce the function of TIGER please?

### ISSUE THREAD

**Issue by Revolution233** [dongzhang0725/PhyloSuite#83]
I have read the manual of the phylosuit, but I can‘t find the introduction of TIGER.

**Comment by dongzhang0725** [comment]
You can check the introduction here: http://mcinerneylab.com/software/tiger/

Revolution233 ***@***.***> 于2023年10月9日周一 21:43写道：

**Comment by Revolution233** [comment]
Thank you for your rapid reply.
